/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Different storage locations supported by the camera.
*/
public class CAMERA_STORAGE_LOCATION {
   public static final int UNKNOWN = 0; /* Unknown | */
   public static final int SDCARD = 1; /* SD card | */
   public static final int INTERNAL_STORAGE = 2; /* The internal storage embedded in the aircraft. | */
   public static final int CAMERA_STORAGE_LOCATION_ENUM_END = 3; /*  | */
}
            