/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class CANOPY_STATUS {
   public static final int CANOPY_STATUS_UNKNOWN = 0; /*  | */
   public static final int CANOPY_STATUS_OPEN = 1; /*  | */
   public static final int CANOPY_STATUS_CLOSE = 2; /*  | */
   public static final int CANOPY_STATUS_ENUM_END = 3; /*  | */
}
            