/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* 
*/
public class CHARGE_PAD_CHARGE_STATUS {
   public static final int CHARGE_PAD_CHARGE_STATUS_UNCHARGE = 0; /*  | */
   public static final int CHARGE_PAD_CHARGE_STATUS_INIT = 1; /*  | */
   public static final int CHARGE_PAD_CHARGE_STATUS_FAST_CHARGE = 2; /*  | */
   public static final int CHARGE_PAD_CHARGE_STATUS_SLOW_CHARGE = 3; /*  | */
   public static final int CHARGE_PAD_CHARGE_STATUS_COMPLETE = 4; /*  | */
   public static final int CHARGE_PAD_CHARGE_STATUS_ENUM_END = 5; /*  | */
}
            