/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Auto or manual control mode
*/
public class MAV_MODE {
   public static final int MAV_MODE_AUTO = 0; /* Fly with missionmanager. | */
   public static final int MAV_MODE_MANUAL = 1; /* Fly with RC override. | */
   public static final int MAV_MODE_ENUM_END = 2; /*  | */
}
            