/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Stages of a downloading process.
*/
public class MEDIAFILE_DOWNLOAD_STAGE {
   public static final int DOWNLOAD_FROM_DRONE = 0; /* Download a file from drone to the onboard computer. | */
   public static final int TRANSMIT = 1; /* Transmit a file through network. | */
   public static final int MEDIAFILE_DOWNLOAD_STAGE_ENUM_END = 2; /*  | */
}
            