/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Media types.
*/
public class MEDIATYPE {
   public static final int UNKNOWN = 0; /* Unknown file type. | */
   public static final int JPEG = 1; /* Image of JPEG format. | */
   public static final int MP4 = 2; /* Video of MP4 format. | */
   public static final int MOV = 3; /* Video of MOV format. | */
   public static final int RAW_DNG = 4; /* Image of DNG format. | */
   public static final int PANORAMA = 5; /* Panarama file type. | */
   public static final int TIFF = 6; /* TIFF file type. | */
   public static final int SHALLOW_FOCUS = 7; /* ShallowFocus file type. | */
   public static final int SEQ = 8; /* TIFF file type. | */
   public static final int TIFF_SEQ = 9; /* SEQ Sequence file type. | */
   public static final int JSON = 10; /* JSON file type. | */
   public static final int PHOTO_FOLDER = 11; /* Photo Folder. | */
   public static final int VIDEO_FOLDER = 12; /* Video Folder. | */
   public static final int MEDIATYPE_ENUM_END = 13; /*  | */
}
            