/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Different mediafile request types, information, thumbnail, preview or raw file.
*/
public class MEDIAFILE_REQUEST_TYPE {
   public static final int INFORMATION = 0; /* Information of a mediafile. | */
   public static final int THUMBNAIL = 1; /* Thumbnail of a mediafile. | */
   public static final int PREVIEW = 2; /* Preview of a mediafile. | */
   public static final int RAW = 3; /* RAW data of a mediafile. | */
   public static final int PAGE = 4; /* One page of a mediafile. | */
   public static final int MEDIAFILE_REQUEST_TYPE_ENUM_END = 5; /*  | */
}
            