/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/** 
* Flags of storage status, internal storage or SD card.
*/
public class STORAGE_STATUS_FLAGS {
   public static final int STORAGE_STATUS_FLAGS_INSERTED = 1; /* Indicate whether SD card is inserted, always 1 for internal storage. | */
   public static final int STORAGE_STATUS_FLAGS_FORMATED = 2; /* Indicate whether the storage is formated. | */
   public static final int STORAGE_STATUS_FLAGS_FULL = 4; /* Indicate whether the storage is full. | */
   public static final int STORAGE_STATUS_FLAGS_ERROR = 8; /* Indicate whether the storage has error. | */
   public static final int STORAGE_STATUS_FLAGS_ENUM_END = 9; /*  | */
}
            