/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE COMMAND_PROGRESS PACKING
package com.MAVLink.DLink;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Report progress of a command.
*/
public class msg_command_progress extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_COMMAND_PROGRESS = 78;
    public static final int MAVLINK_MSG_LENGTH = 3;
    private static final long serialVersionUID = MAVLINK_MSG_ID_COMMAND_PROGRESS;


      
    /**
    * Command ID.
    */
    public short command;
      
    /**
    * Total steps of the command.
    */
    public short step_total;
      
    /**
    * The step just complete.
    */
    public short step_complete;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 1;
        packet.compid = 1;
        packet.msgid = MAVLINK_MSG_ID_COMMAND_PROGRESS;
              
        packet.payload.putUnsignedByte(command);
              
        packet.payload.putUnsignedByte(step_total);
              
        packet.payload.putUnsignedByte(step_complete);
        
        return packet;
    }

    /**
    * Decode a command_progress message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.command = payload.getUnsignedByte();
              
        this.step_total = payload.getUnsignedByte();
              
        this.step_complete = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_command_progress(){
        msgid = MAVLINK_MSG_ID_COMMAND_PROGRESS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_command_progress(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_COMMAND_PROGRESS;
        unpack(mavLinkPacket.payload);        
    }

          
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_COMMAND_PROGRESS - sysid:"+sysid+" compid:"+compid+" command:"+command+" step_total:"+step_total+" step_complete:"+step_complete+"";
    }
}
        