/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE CHARGEPAD_STATUS PACKING
package com.MAVLink.DLink;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Status of chargepad.
*/
public class msg_chargepad_status extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_CHARGEPAD_STATUS = 2;
    public static final int MAVLINK_MSG_LENGTH = 19;
    private static final long serialVersionUID = MAVLINK_MSG_ID_CHARGEPAD_STATUS;


      
    /**
    * Flags.
    */
    public long status_flags;
      
    /**
    * Indicate charge voltage
    */
    public long charge_voltage;
      
    /**
    * Indicate charge current.
    */
    public long charge_current;
      
    /**
    * Reserved
    */
    public long reserved;
      
    /**
    * Indicate position of positioning bars.
    */
    public short bar_position;
      
    /**
    * Indicate charge status.
    */
    public short charge_status;
      
    /**
    * Indicate canopy position.
    */
    public short canopy_status;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 1;
        packet.compid = 1;
        packet.msgid = MAVLINK_MSG_ID_CHARGEPAD_STATUS;
              
        packet.payload.putUnsignedInt(status_flags);
              
        packet.payload.putUnsignedInt(charge_voltage);
              
        packet.payload.putUnsignedInt(charge_current);
              
        packet.payload.putUnsignedInt(reserved);
              
        packet.payload.putUnsignedByte(bar_position);
              
        packet.payload.putUnsignedByte(charge_status);
              
        packet.payload.putUnsignedByte(canopy_status);
        
        return packet;
    }

    /**
    * Decode a chargepad_status message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.status_flags = payload.getUnsignedInt();
              
        this.charge_voltage = payload.getUnsignedInt();
              
        this.charge_current = payload.getUnsignedInt();
              
        this.reserved = payload.getUnsignedInt();
              
        this.bar_position = payload.getUnsignedByte();
              
        this.charge_status = payload.getUnsignedByte();
              
        this.canopy_status = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_chargepad_status(){
        msgid = MAVLINK_MSG_ID_CHARGEPAD_STATUS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_chargepad_status(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_CHARGEPAD_STATUS;
        unpack(mavLinkPacket.payload);        
    }

                  
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_CHARGEPAD_STATUS - sysid:"+sysid+" compid:"+compid+" status_flags:"+status_flags+" charge_voltage:"+charge_voltage+" charge_current:"+charge_current+" reserved:"+reserved+" bar_position:"+bar_position+" charge_status:"+charge_status+" canopy_status:"+canopy_status+"";
    }
}
        