/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE CAMERA_SETTINGS PACKING
package com.MAVLink.DLink;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Settings of a camera, can be requested using MAV_CMD_REQUEST_CAMERA_SETTINGS.
*/
public class msg_camera_settings extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_CAMERA_SETTINGS = 160;
    public static final int MAVLINK_MSG_LENGTH = 13;
    private static final long serialVersionUID = MAVLINK_MSG_ID_CAMERA_SETTINGS;


      
    /**
    * Timestamp (time since system boot).
    */
    public long time_boot_ms;
      
    /**
    * Current zoom level (0.0 to 100.0, NaN if not known)
    */
    public float zoomLevel;
      
    /**
    * Current focus level (0.0 to 100.0, NaN if not known)
    */
    public float focusLevel;
      
    /**
    * Camera mode
    */
    public short mode_id;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 1;
        packet.compid = 1;
        packet.msgid = MAVLINK_MSG_ID_CAMERA_SETTINGS;
              
        packet.payload.putUnsignedInt(time_boot_ms);
              
        packet.payload.putFloat(zoomLevel);
              
        packet.payload.putFloat(focusLevel);
              
        packet.payload.putUnsignedByte(mode_id);
        
        return packet;
    }

    /**
    * Decode a camera_settings message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.time_boot_ms = payload.getUnsignedInt();
              
        this.zoomLevel = payload.getFloat();
              
        this.focusLevel = payload.getFloat();
              
        this.mode_id = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_camera_settings(){
        msgid = MAVLINK_MSG_ID_CAMERA_SETTINGS;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_camera_settings(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_CAMERA_SETTINGS;
        unpack(mavLinkPacket.payload);        
    }

            
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_CAMERA_SETTINGS - sysid:"+sysid+" compid:"+compid+" time_boot_ms:"+time_boot_ms+" zoomLevel:"+zoomLevel+" focusLevel:"+focusLevel+" mode_id:"+mode_id+"";
    }
}
        