/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MEDIAFILE_REQUEST_LIST PACKING
package com.MAVLink.DLink;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Get the number of files of the SD card or the internal storage.
*/
public class msg_mediafile_request_list extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_MEDIAFILE_REQUEST_LIST = 150;
    public static final int MAVLINK_MSG_LENGTH = 1;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MEDIAFILE_REQUEST_LIST;


      
    /**
    * Target storage location to request mediafile, SD card or internal storage.
    */
    public short storage_location;
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 1;
        packet.compid = 1;
        packet.msgid = MAVLINK_MSG_ID_MEDIAFILE_REQUEST_LIST;
              
        packet.payload.putUnsignedByte(storage_location);
        
        return packet;
    }

    /**
    * Decode a mediafile_request_list message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.storage_location = payload.getUnsignedByte();
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_mediafile_request_list(){
        msgid = MAVLINK_MSG_ID_MEDIAFILE_REQUEST_LIST;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_mediafile_request_list(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_MEDIAFILE_REQUEST_LIST;
        unpack(mavLinkPacket.payload);        
    }

      
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_MEDIAFILE_REQUEST_LIST - sysid:"+sysid+" compid:"+compid+" storage_location:"+storage_location+"";
    }
}
        