/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE MEDIAFILE_INFORMATION PACKING
package com.MAVLink.DLink;
import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
        
/**
* Informations of a mediafile.
*/
public class msg_mediafile_information extends MAVLinkMessage{

    public static final int MAVLINK_MSG_ID_MEDIAFILE_INFORMATION = 153;
    public static final int MAVLINK_MSG_LENGTH = 66;
    private static final long serialVersionUID = MAVLINK_MSG_ID_MEDIAFILE_INFORMATION;


      
    /**
    * The size of the mediafile.
    */
    public long file_size;
      
    /**
    * The num of pages of a mediafile.
    */
    public long total_page;
      
    /**
    * Index of the requested file on the target storage location.
    */
    public int index;
      
    /**
    * The storage location, SD card or the internal storage.
    */
    public short storage_location;
      
    /**
    * The filename of the mediafile.
    */
    public byte file_name[] = new byte[20];
      
    /**
    * The type of the mediafile.
    */
    public short file_type;
      
    /**
    * The created date and time of the mediafile.
    */
    public byte created_at[] = new byte[30];
    

    /**
    * Generates the payload for a mavlink message for a message of this type
    * @return
    */
    public MAVLinkPacket pack(){
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH);
        packet.sysid = 1;
        packet.compid = 1;
        packet.msgid = MAVLINK_MSG_ID_MEDIAFILE_INFORMATION;
              
        packet.payload.putUnsignedLong(file_size);
              
        packet.payload.putUnsignedInt(total_page);
              
        packet.payload.putUnsignedShort(index);
              
        packet.payload.putUnsignedByte(storage_location);
              
        
        for (int i = 0; i < file_name.length; i++) {
            packet.payload.putByte(file_name[i]);
        }
                    
              
        packet.payload.putUnsignedByte(file_type);
              
        
        for (int i = 0; i < created_at.length; i++) {
            packet.payload.putByte(created_at[i]);
        }
                    
        
        return packet;
    }

    /**
    * Decode a mediafile_information message into this class fields
    *
    * @param payload The message to decode
    */
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();
              
        this.file_size = payload.getUnsignedLong();
              
        this.total_page = payload.getUnsignedInt();
              
        this.index = payload.getUnsignedShort();
              
        this.storage_location = payload.getUnsignedByte();
              
         
        for (int i = 0; i < this.file_name.length; i++) {
            this.file_name[i] = payload.getByte();
        }
                
              
        this.file_type = payload.getUnsignedByte();
              
         
        for (int i = 0; i < this.created_at.length; i++) {
            this.created_at[i] = payload.getByte();
        }
                
        
    }

    /**
    * Constructor for a new message, just initializes the msgid
    */
    public msg_mediafile_information(){
        msgid = MAVLINK_MSG_ID_MEDIAFILE_INFORMATION;
    }

    /**
    * Constructor for a new message, initializes the message with the payload
    * from a mavlink packet
    *
    */
    public msg_mediafile_information(MAVLinkPacket mavLinkPacket){
        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.msgid = MAVLINK_MSG_ID_MEDIAFILE_INFORMATION;
        unpack(mavLinkPacket.payload);        
    }

             
    /**
    * Sets the buffer of this message with a string, adds the necessary padding
    */
    public void setFile_Name(String str) {
        int len = Math.min(str.length(), 20);
        for (int i=0; i<len; i++) {
            file_name[i] = (byte) str.charAt(i);
        }

        for (int i=len; i<20; i++) {            // padding for the rest of the buffer
            file_name[i] = 0;
        }
    }

    /**
    * Gets the message, formated as a string
    */
    public String getFile_Name() {
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < 20; i++) {
            if (file_name[i] != 0)
                buf.append((char) file_name[i]);
            else
                break;
        }
        return buf.toString();

    }
                            
    /**
    * Sets the buffer of this message with a string, adds the necessary padding
    */
    public void setCreated_At(String str) {
        int len = Math.min(str.length(), 30);
        for (int i=0; i<len; i++) {
            created_at[i] = (byte) str.charAt(i);
        }

        for (int i=len; i<30; i++) {            // padding for the rest of the buffer
            created_at[i] = 0;
        }
    }

    /**
    * Gets the message, formated as a string
    */
    public String getCreated_At() {
        StringBuffer buf = new StringBuffer();
        for (int i = 0; i < 30; i++) {
            if (created_at[i] != 0)
                buf.append((char) created_at[i]);
            else
                break;
        }
        return buf.toString();

    }
                         
    /**
    * Returns a string with the MSG name and data
    */
    public String toString(){
        return "MAVLINK_MSG_ID_MEDIAFILE_INFORMATION - sysid:"+sysid+" compid:"+compid+" file_size:"+file_size+" total_page:"+total_page+" index:"+index+" storage_location:"+storage_location+" file_name:"+file_name+" file_type:"+file_type+" created_at:"+created_at+"";
    }
}
        